name: macos build
on: [push]
jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - name: cache brew downloads
      uses: actions/cache@v3
      with:
        path: ~/Library/Caches/Homebrew/downloads/
        key: brew-cache
    - name: Install deps
      run: brew install bzip2 ffmpeg hunspell libao libtiff libvorbis lzo opencc xz zstd libao libogg pkg-config qt@5
    - name: debug info
      run: brew info libvorbis
    - name: set env
      run: |
        echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
        # echo "LDFLAGS=-L/usr/local/opt/qt@5/lib" >> "$GITHUB_ENV"
        # echo "CPPFLAGS=-I/usr/local/opt/qt@5/include" >> "$GITHUB_ENV"
    - name: qmake
      run: qmake "CONFIG+=use_qtwebengine" "CONFIG+=no_epwing_support" "CONFIG+=chinese_conversion_support" "CONFIG+=zim_support"
    - name: build
      run: make -j8
    - name: upload app
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: GoldenDict.app
